[package]
name = "coral-captcha"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
image.workspace = true
fontdue.workspace = true
nalgebra.workspace = true
thiserror.workspace = true