[package]
name = "coral-runtime"
version = "0.1.0"
edition.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
core_affinity.workspace = true
thiserror.workspace  = true
tokio.workspace  = true

[dev-dependencies]
num_cpus.workspace  = true