[package]
name = "coral-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
core_affinity = "0.8"
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }

[dev-dependencies]
num_cpus = "1.16"