[h2.server_conf]
port = 9000
domain = "server.test.com"

[h2.tls_conf]
# ca = "./cicd/self_sign_cert/ca"
cert = "./cicd/self_sign_cert/server.crt"
key = "./cicd/self_sign_cert/server.key"
alpn = ["h2", "http/1.1"]

[h3.server_conf]
port = 9001
domain = "server.test.com"

[h3.tls_conf]
# ca = "./cicd/self_sign_cert/ca"
cert = "./cicd/self_sign_cert/server.crt"
key = "./cicd/self_sign_cert/server.key"
alpn = ["h3", "h3-29", "h3-28", "h3-27"]

[log_conf]
# dir = "/root/tmp/log"
prefix = "server"

[rt_conf]
cpui = 0
nums = 1

[assets]
path = "/"
dir = ""

[db.pool]
max_connections = 5

[db.postgres]
host = ""
port = 5432
# socket = ""
username = "postgres"
password = ""
database = "postgres"
ssl_mode = "prefer" # or verify-ca
# ssl_root_cert = ""
# ssl_client_cert = ""
# ssl_client_key = ""
# statement_cache_capacity = 100
# application_name = ""
# log_settings = {}

[redis.Single]
host = ""
port = 6379
insecure = false
# tls_params = { root_cert_store = "", client_cert = "", client_key = "" }
db = 0
# username = ""
password = ""
protocol = 1 # 0 => RESP2   1 => RESP3

[redis.Single.config]
Manager = {
  # exponent_base = 0
  # factor = 0
  # number_of_retries = 0
  # max_delay = 0
  # response_timeout = 0
  # connection_timeout = 0
}

# [redis.Cluster]
# password = ""
# username = ""
# read_from_replicas = false
# insecure = false
# tls_params = { root_cert_store = "", client_cert = "", client_key = "" }
# connection_timeout = 0
# response_timeout = 0
# protocol = 0

# [redis.Cluster.retry_params]
# number_of_retries = 0
# max_wait_time = 0
# min_wait_time = 0
# exponent_base = 0
# factor = 0


# Vec<ConnectionInfo>
# [[redis.Cluster.info]]
# host = ""
# port = 6379
# insecure = false
# # tls_params = { root_cert_store = "", client_cert = "", client_key = "" }
# db = 0
# # username = ""
# password = ""
# protocol = 0
