[package]
name = "coral-conf"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
coral-macro.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0"
toml.workspace = true
