// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Token {
    #[prost(string, tag = "1")]
    pub alg: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub typ: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub iss: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub sub: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub aud: ::prost::alloc::string::String,
    #[prost(uint64, tag = "6")]
    pub exp: u64,
    #[prost(uint64, tag = "7")]
    pub nbf: u64,
    #[prost(uint64, tag = "8")]
    pub iat: u64,
    /// string sig = 10;
    #[prost(uint64, tag = "9")]
    pub jti: u64,
}
