[package]
name = "coral-log"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
bytes = "1"
chrono = "0.4"
prost = "0.13"
prost-types = "0.13"
thiserror = "1.0"
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", default-features = false, features = ["smallvec", "fmt", "ansi", "tracing-log", "std", "chrono"] }

[build-dependencies]
prost-build = "0.13"
