[package]
name = "coral-log"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = ["smallvec", "fmt", "ansi", "tracing-log", "std", "chrono"] }

[build-dependencies]
prost-build = "0.13"
